### PR TITLE
company specific schedule endpoint

### PR DESCRIPTION
**Pull request by owenjaques**
# Description
This PR adds the company specific schedule endpoint that is required for the plug and play demo. /schedule/company/<company#> will return a list of schedules as generated from either company one or two.  I also noticed out docs said schedules but our actual endpoint was schedule so I changed them both to the plural since it matched out other endpoints.

Fixes https://github.com/seng499-company1/backend/issues/58
## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [x] Tested out each endpoint and saw that they returned OK
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have linted my code and fixed all issues

### CODE REVIEW

**Comment by owenjaques** [comment]
Algo 1 requires python > 3.10 so this is causing some issues with our CI :( I personally had to upgrade my machine to make it work.

**Comment by owenjaques** [comment]
I've gone ahead and disabled pylint for 3.8 and 3.9 in this PR since we will have to use 3.10 unless algo changes their min required version.

**Comment by ekanemeinstein** [comment]
> o

Makes sense

**Comment by ekanemeinstein** [comment]
Ready for review? It appears as a draft

**Comment by owenjaques** [comment]
> Ready for review? It appears as a draft

Company 2 still hasn't given us instructions on how to call their algorithm! I put it in draft because that code isnt in yet. That being said if they dont get it to us in time everything else should be good to  go.

**Comment by ekanemeinstein** [comment]
> > Ready for review? It appears as a draft
> 
> Company 2 still hasn't given us instructions on how to call their algorithm! I put it in draft because that code isnt in yet. That being said if they dont get it to us in time everything else should be good to go.

Cool, good job.

**Comment by owenjaques** [comment]
Linting is failing. I'm pretty sure its because company 2s algo team code is hosted as a test project. Not sure if this is fixable / I could look at it in next sprint.

**Review by ekanemeinstein — APPROVED** [review]

**Pull request merged**
